import type { Story } from '$lib/stories/types';

const stories: Story[] = [
  {
    id: 1,
    level: 1,
    number: 101,
    language: 'ko-kr',
    title: '분식집',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 2,
    level: 1,
    number: 102,
    language: 'ko-kr',
    title: '문방구',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 3,
    level: 1,
    number: 103,
    language: 'ko-kr',
    title: '야생동물',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 4,
    level: 1,
    number: 104,
    language: 'ko-kr',
    title: '내 기분은',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 5,
    level: 1,
    number: 105,
    language: 'ko-kr',
    title: '세는 말',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 6,
    level: 1,
    number: 106,
    language: 'ko-kr',
    title: '눈 오는 날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 7,
    level: 1,
    number: 107,
    language: 'ko-kr',
    title: '자전거',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 8,
    level: 1,
    number: 108,
    language: 'ko-kr',
    title: '케이크 만들기',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 9,
    level: 1,
    number: 109,
    language: 'ko-kr',
    title: '김밥 만들기',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 10,
    level: 1,
    number: 110,
    language: 'ko-kr',
    title: '콩을 심으면',
    topics: new Set([
      '자연',
    ]),
  },
  {
    id: 11,
    level: 1,
    number: 111,
    language: 'ko-kr',
    title: '사자가 바다에 가요',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 12,
    level: 1,
    number: 201,
    language: 'ko-kr',
    title: '나무',
    topics: new Set([
      '자연',
    ]),
  },
  {
    id: 13,
    level: 1,
    number: 202,
    language: 'ko-kr',
    title: '무슨 맛일까요?',
    topics: new Set([
      '음식',
    ]),
  },
  {
    id: 14,
    level: 1,
    number: 203,
    language: 'ko-kr',
    title: '나는 누구일까요?',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 15,
    level: 1,
    number: 204,
    language: 'ko-kr',
    title: '다람쥐와 도토리',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 16,
    level: 1,
    number: 205,
    language: 'ko-kr',
    title: '반대말 놀이',
    topics: new Set(),
  },
  {
    id: 17,
    level: 1,
    number: 206,
    language: 'ko-kr',
    title: '혀를 내밀어 봐',
    topics: new Set([
      '동물',
      '자연',
    ]),
  },
  {
    id: 18,
    level: 2,
    number: 207,
    language: 'ko-kr',
    title: '무엇을 타고 갈까?',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 19,
    level: 2,
    number: 208,
    language: 'ko-kr',
    title: '예쁜 두 손',
    topics: new Set(),
  },
  {
    id: 20,
    level: 2,
    number: 209,
    language: 'ko-kr',
    title: '바르게 바르게',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 21,
    level: 2,
    number: 210,
    language: 'ko-kr',
    title: '어떤 기분일까요?',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 22,
    level: 1,
    number: 211,
    language: 'ko-kr',
    title: '그려 주세요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 23,
    level: 1,
    number: 212,
    language: 'ko-kr',
    title: '물놀이',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 24,
    level: 2,
    number: 301,
    language: 'ko-kr',
    title: '시장 가는 날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 25,
    level: 2,
    number: 302,
    language: 'ko-kr',
    title: '뚱뚱한 왕과 홀쭉한 개',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 26,
    level: 1,
    number: 303,
    language: 'ko-kr',
    title: '할 수 있어요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 27,
    level: 2,
    number: 304,
    language: 'ko-kr',
    title: '수탉과 지렁이',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 28,
    level: 2,
    number: 305,
    language: 'ko-kr',
    title: '오늘 나는',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 29,
    level: 2,
    number: 306,
    language: 'ko-kr',
    title: '신발을 찾아라',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 30,
    level: 2,
    number: 307,
    language: 'ko-kr',
    title: '어떤 병원으로 가야 할까?',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 31,
    level: 2,
    number: 308,
    language: 'ko-kr',
    title: '한가위',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 32,
    level: 2,
    number: 309,
    language: 'ko-kr',
    title: '다른 나라의 인사말',
    topics: new Set(),
  },
  {
    id: 33,
    level: 2,
    number: 310,
    language: 'ko-kr',
    title: '우리 가족',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 34,
    level: 2,
    number: 401,
    language: 'ko-kr',
    title: '지하철을 타고',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 35,
    level: 2,
    number: 402,
    language: 'ko-kr',
    title: '심부름',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 36,
    level: 3,
    number: 403,
    language: 'ko-kr',
    title: '생쥐와 사자',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 37,
    level: 3,
    number: 404,
    language: 'ko-kr',
    title: '아기 사슴 로미',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 38,
    level: 2,
    number: 405,
    language: 'ko-kr',
    title: '우리는 친구',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 39,
    level: 2,
    number: 406,
    language: 'ko-kr',
    title: '찾아 보아요',
    topics: new Set(),
  },
  {
    id: 40,
    level: 3,
    number: 407,
    language: 'ko-kr',
    title: '동네 한 바퀴',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 41,
    level: 3,
    number: 408,
    language: 'ko-kr',
    title: '학교 가는 길',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 42,
    level: 3,
    number: 409,
    language: 'ko-kr',
    title: '버스를 타요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 43,
    level: 2,
    number: 410,
    language: 'ko-kr',
    title: '설날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 44,
    level: 2,
    number: 411,
    language: 'ko-kr',
    title: '내 친구 고양이',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 45,
    level: 2,
    number: 412,
    language: 'ko-kr',
    title: '이천 원으로 뭘 할까?',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 46,
    level: 3,
    number: 501,
    language: 'ko-kr',
    title: '도서관 가는 날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 47,
    level: 3,
    number: 502,
    language: 'ko-kr',
    title: '풍선 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 48,
    level: 3,
    number: 503,
    language: 'ko-kr',
    title: '사이좋게 놀아요',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 49,
    level: 3,
    number: 504,
    language: 'ko-kr',
    title: '달나라로 떠나자',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 50,
    level: 3,
    number: 505,
    language: 'ko-kr',
    title: '나무 위의 모험',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 51,
    level: 3,
    number: 506,
    language: 'ko-kr',
    title: '거인과 작은 새',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 52,
    level: 3,
    number: 507,
    language: 'ko-kr',
    title: '혼자 병원에 갔어요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 53,
    level: 3,
    number: 508,
    language: 'ko-kr',
    title: '밥상을 차려요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 54,
    level: 4,
    number: 509,
    language: 'ko-kr',
    title: '우체국에 갔어요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 55,
    level: 3,
    number: 510,
    language: 'ko-kr',
    title: '즐거운 학교 생활',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 56,
    level: 4,
    number: 601,
    language: 'ko-kr',
    title: '여러 가지 배',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 57,
    level: 4,
    number: 602,
    language: 'ko-kr',
    title: '바닷속 탐험',
    topics: new Set([
      '동물',
      '자연',
    ]),
  },
  {
    id: 58,
    level: 4,
    number: 603,
    language: 'ko-kr',
    title: '뱀이 다리가 없는 이유',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 59,
    level: 5,
    number: 604,
    language: 'ko-kr',
    title: '게으른 거미 아난시',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 60,
    level: 3,
    number: 605,
    language: 'ko-kr',
    title: '노란 무당벌레 라라',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 61,
    level: 4,
    number: 606,
    language: 'ko-kr',
    title: '할아버지의 정원',
    topics: new Set([
      '자연',
    ]),
  },
  {
    id: 62,
    level: 4,
    number: 607,
    language: 'ko-kr',
    title: '한복을 입어요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 63,
    level: 5,
    number: 608,
    language: 'ko-kr',
    title: '나는 커서 어떤 일을 할까?',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 64,
    level: 4,
    number: 609,
    language: 'ko-kr',
    title: '할머니 할아버지와 저녁을 먹어요',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 65,
    level: 4,
    number: 610,
    language: 'ko-kr',
    title: '준우의 토요일',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 66,
    level: 4,
    number: 611,
    language: 'ko-kr',
    title: '손톱 먹은 들쥐',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 67,
    level: 5,
    number: 701,
    language: 'ko-kr',
    title: '로봇',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 68,
    level: 5,
    number: 702,
    language: 'ko-kr',
    title: '지구온난화',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 69,
    level: 5,
    number: 703,
    language: 'ko-kr',
    title: '미세먼지',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 70,
    level: 5,
    number: 704,
    language: 'ko-kr',
    title: '드론',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 71,
    level: 5,
    number: 705,
    language: 'ko-kr',
    title: '코딩',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 72,
    level: 5,
    number: 706,
    language: 'ko-kr',
    title: '태양계',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 73,
    level: 5,
    number: 707,
    language: 'ko-kr',
    title: '화산과 지진',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 74,
    level: 5,
    number: 708,
    language: 'ko-kr',
    title: '생태계',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 75,
    level: 5,
    number: 709,
    language: 'ko-kr',
    title: '몸속에 들어간 음식은 어떻게 될까?',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 76,
    level: 4,
    number: 710,
    language: 'ko-kr',
    title: '온몸으로 느껴요',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 77,
    level: 5,
    number: 711,
    language: 'ko-kr',
    title: '물의 순환',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 78,
    level: 5,
    number: 712,
    language: 'ko-kr',
    title: '공룡',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 79,
    level: 5,
    number: 713,
    language: 'ko-kr',
    title: '우리 주위의 전기',
    topics: new Set([
      '과학',
    ]),
  },
  {
    id: 80,
    level: 5,
    number: 714,
    language: 'ko-kr',
    title: '지구와 달',
    topics: new Set([
      '과학',
      '자연',
    ]),
  },
  {
    id: 81,
    level: 5,
    number: 715,
    language: 'ko-kr',
    title: '돈은 어떻게 변해 왔을까?',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 82,
    level: 6,
    number: 716,
    language: 'ko-kr',
    title: '마법의 가루',
    topics: new Set(),
  },
  {
    id: 83,
    level: 5,
    number: 717,
    language: 'ko-kr',
    title: '새들의 왕',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 84,
    level: 4,
    number: 718,
    language: 'ko-kr',
    title: '내 모습 그대로',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 85,
    level: 5,
    number: 719,
    language: 'ko-kr',
    title: '이상한 만두 장수',
    topics: new Set([
      '음식',
    ]),
  },
  {
    id: 86,
    level: 4,
    number: 720,
    language: 'ko-kr',
    title: '젊어지는 샘물',
    topics: new Set(),
  },
  {
    id: 87,
    level: 5,
    number: 721,
    language: 'ko-kr',
    title: '도깨비감투',
    topics: new Set(),
  },
  {
    id: 88,
    level: 6,
    number: 801,
    language: 'en-ph',
    title: '락롱꽌과 아우꺼',
    topics: new Set(),
  },
  {
    id: 89,
    level: 6,
    number: 801,
    language: 'ko-kr',
    title: '락롱꽌과 아우꺼',
    topics: new Set(),
  },
  {
    id: 90,
    level: 6,
    number: 801,
    language: 'th-th',
    title: '락롱꽌과 아우꺼',
    topics: new Set(),
  },
  {
    id: 91,
    level: 6,
    number: 801,
    language: 'vi-vn',
    title: '락롱꽌과 아우꺼',
    topics: new Set(),
  },
  {
    id: 92,
    level: 6,
    number: 801,
    language: 'zh-cn',
    title: '락롱꽌과 아우꺼',
    topics: new Set(),
  },
  {
    id: 93,
    level: 6,
    number: 802,
    language: 'en-ph',
    title: '황냔의 하루',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 94,
    level: 6,
    number: 802,
    language: 'ko-kr',
    title: '황냔의 하루',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 95,
    level: 6,
    number: 802,
    language: 'th-th',
    title: '황냔의 하루',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 96,
    level: 6,
    number: 802,
    language: 'vi-vn',
    title: '황냔의 하루',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 97,
    level: 6,
    number: 802,
    language: 'zh-cn',
    title: '황냔의 하루',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 98,
    level: 6,
    number: 803,
    language: 'en-ph',
    title: '마이의 베트남 설날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 99,
    level: 6,
    number: 803,
    language: 'ko-kr',
    title: '마이의 베트남 설날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 100,
    level: 6,
    number: 803,
    language: 'th-th',
    title: '마이의 베트남 설날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 101,
    level: 6,
    number: 803,
    language: 'vi-vn',
    title: '마이의 베트남 설날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 102,
    level: 6,
    number: 803,
    language: 'zh-cn',
    title: '마이의 베트남 설날',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 103,
    level: 6,
    number: 804,
    language: 'en-ph',
    title: '베트남 도시 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 104,
    level: 6,
    number: 804,
    language: 'ko-kr',
    title: '베트남 도시 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 105,
    level: 6,
    number: 804,
    language: 'th-th',
    title: '베트남 도시 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 106,
    level: 6,
    number: 804,
    language: 'vi-vn',
    title: '베트남 도시 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 107,
    level: 6,
    number: 804,
    language: 'zh-cn',
    title: '베트남 도시 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 108,
    level: 6,
    number: 805,
    language: 'en-ph',
    title: '베트남 음식점에 갔어요',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 109,
    level: 6,
    number: 805,
    language: 'ko-kr',
    title: '베트남 음식점에 갔어요',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 110,
    level: 6,
    number: 805,
    language: 'th-th',
    title: '베트남 음식점에 갔어요',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 111,
    level: 6,
    number: 805,
    language: 'vi-vn',
    title: '베트남 음식점에 갔어요',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 112,
    level: 6,
    number: 805,
    language: 'zh-cn',
    title: '베트남 음식점에 갔어요',
    topics: new Set([
      '생활',
      '음식',
    ]),
  },
  {
    id: 113,
    level: 6,
    number: 806,
    language: 'en-ph',
    title: '중국 만두 이야기',
    topics: new Set([
      '음식',
    ]),
  },
  {
    id: 114,
    level: 6,
    number: 806,
    language: 'ko-kr',
    title: '중국 만두 이야기',
    topics: new Set([
      '음식',
    ]),
  },
  {
    id: 115,
    level: 6,
    number: 806,
    language: 'th-th',
    title: '중국 만두 이야기',
    topics: new Set([
      '음식',
    ]),
  },
  {
    id: 116,
    level: 6,
    number: 806,
    language: 'vi-vn',
    title: '중국 만두 이야기',
    topics: new Set([
      '음식',
    ]),
  },
  {
    id: 117,
    level: 6,
    number: 806,
    language: 'zh-cn',
    title: '중국 만두 이야기',
    topics: new Set([
      '음식',
    ]),
  },
  {
    id: 118,
    level: 6,
    number: 807,
    language: 'en-ph',
    title: '백사전: 중국의 하얀 뱀 전설',
    topics: new Set(),
  },
  {
    id: 119,
    level: 6,
    number: 807,
    language: 'ko-kr',
    title: '백사전: 중국의 하얀 뱀 전설',
    topics: new Set(),
  },
  {
    id: 120,
    level: 6,
    number: 807,
    language: 'th-th',
    title: '백사전: 중국의 하얀 뱀 전설',
    topics: new Set(),
  },
  {
    id: 121,
    level: 6,
    number: 807,
    language: 'vi-vn',
    title: '백사전: 중국의 하얀 뱀 전설',
    topics: new Set(),
  },
  {
    id: 122,
    level: 6,
    number: 807,
    language: 'zh-cn',
    title: '백사전: 중국의 하얀 뱀 전설',
    topics: new Set(),
  },
  {
    id: 123,
    level: 6,
    number: 808,
    language: 'en-ph',
    title: '중국 베이징에 갔어요',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 124,
    level: 6,
    number: 808,
    language: 'ko-kr',
    title: '중국 베이징에 갔어요',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 125,
    level: 6,
    number: 808,
    language: 'th-th',
    title: '중국 베이징에 갔어요',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 126,
    level: 6,
    number: 808,
    language: 'vi-vn',
    title: '중국 베이징에 갔어요',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 127,
    level: 6,
    number: 808,
    language: 'zh-cn',
    title: '중국 베이징에 갔어요',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 128,
    level: 6,
    number: 809,
    language: 'en-ph',
    title: '즐거운 춘절 맞이',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 129,
    level: 6,
    number: 809,
    language: 'ko-kr',
    title: '즐거운 춘절 맞이',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 130,
    level: 6,
    number: 809,
    language: 'th-th',
    title: '즐거운 춘절 맞이',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 131,
    level: 6,
    number: 809,
    language: 'vi-vn',
    title: '즐거운 춘절 맞이',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 132,
    level: 6,
    number: 809,
    language: 'zh-cn',
    title: '즐거운 춘절 맞이',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 133,
    level: 6,
    number: 810,
    language: 'en-ph',
    title: '후예와 항아',
    topics: new Set(),
  },
  {
    id: 134,
    level: 6,
    number: 810,
    language: 'ko-kr',
    title: '후예와 항아',
    topics: new Set(),
  },
  {
    id: 135,
    level: 6,
    number: 810,
    language: 'th-th',
    title: '후예와 항아',
    topics: new Set(),
  },
  {
    id: 136,
    level: 6,
    number: 810,
    language: 'vi-vn',
    title: '후예와 항아',
    topics: new Set(),
  },
  {
    id: 137,
    level: 6,
    number: 810,
    language: 'zh-cn',
    title: '후예와 항아',
    topics: new Set(),
  },
  {
    id: 138,
    level: 6,
    number: 811,
    language: 'en-ph',
    title: '쌀의 전설',
    topics: new Set(),
  },
  {
    id: 139,
    level: 6,
    number: 811,
    language: 'ko-kr',
    title: '쌀의 전설',
    topics: new Set(),
  },
  {
    id: 140,
    level: 6,
    number: 811,
    language: 'th-th',
    title: '쌀의 전설',
    topics: new Set(),
  },
  {
    id: 141,
    level: 6,
    number: 811,
    language: 'vi-vn',
    title: '쌀의 전설',
    topics: new Set(),
  },
  {
    id: 142,
    level: 6,
    number: 811,
    language: 'zh-cn',
    title: '쌀의 전설',
    topics: new Set(),
  },
  {
    id: 143,
    level: 6,
    number: 812,
    language: 'en-ph',
    title: '필리핀의 크리스마스',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 144,
    level: 6,
    number: 812,
    language: 'ko-kr',
    title: '필리핀의 크리스마스',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 145,
    level: 6,
    number: 812,
    language: 'th-th',
    title: '필리핀의 크리스마스',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 146,
    level: 6,
    number: 812,
    language: 'vi-vn',
    title: '필리핀의 크리스마스',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 147,
    level: 6,
    number: 812,
    language: 'zh-cn',
    title: '필리핀의 크리스마스',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 148,
    level: 6,
    number: 813,
    language: 'en-ph',
    title: '일곱 번째 생일 파티',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 149,
    level: 6,
    number: 813,
    language: 'ko-kr',
    title: '일곱 번째 생일 파티',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 150,
    level: 6,
    number: 813,
    language: 'th-th',
    title: '일곱 번째 생일 파티',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 151,
    level: 6,
    number: 813,
    language: 'vi-vn',
    title: '일곱 번째 생일 파티',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 152,
    level: 6,
    number: 813,
    language: 'zh-cn',
    title: '일곱 번째 생일 파티',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 153,
    level: 6,
    number: 814,
    language: 'en-ph',
    title: '빨간 트라이시클 엔텡',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 154,
    level: 6,
    number: 814,
    language: 'ko-kr',
    title: '빨간 트라이시클 엔텡',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 155,
    level: 6,
    number: 814,
    language: 'th-th',
    title: '빨간 트라이시클 엔텡',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 156,
    level: 6,
    number: 814,
    language: 'vi-vn',
    title: '빨간 트라이시클 엔텡',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 157,
    level: 6,
    number: 814,
    language: 'zh-cn',
    title: '빨간 트라이시클 엔텡',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 158,
    level: 6,
    number: 815,
    language: 'en-ph',
    title: '노란 지프니 포기',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 159,
    level: 6,
    number: 815,
    language: 'ko-kr',
    title: '노란 지프니 포기',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 160,
    level: 6,
    number: 815,
    language: 'th-th',
    title: '노란 지프니 포기',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 161,
    level: 6,
    number: 815,
    language: 'vi-vn',
    title: '노란 지프니 포기',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 162,
    level: 6,
    number: 815,
    language: 'zh-cn',
    title: '노란 지프니 포기',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 163,
    level: 6,
    number: 816,
    language: 'en-ph',
    title: '필리핀에 대한 아홉 가지 사실',
    topics: new Set(),
  },
  {
    id: 164,
    level: 6,
    number: 816,
    language: 'ko-kr',
    title: '필리핀에 대한 아홉 가지 사실',
    topics: new Set(),
  },
  {
    id: 165,
    level: 6,
    number: 816,
    language: 'th-th',
    title: '필리핀에 대한 아홉 가지 사실',
    topics: new Set(),
  },
  {
    id: 166,
    level: 6,
    number: 816,
    language: 'vi-vn',
    title: '필리핀에 대한 아홉 가지 사실',
    topics: new Set(),
  },
  {
    id: 167,
    level: 6,
    number: 816,
    language: 'zh-cn',
    title: '필리핀에 대한 아홉 가지 사실',
    topics: new Set(),
  },
  {
    id: 168,
    level: 6,
    number: 817,
    language: 'en-ph',
    title: '금빛 물고기 이야기',
    topics: new Set(),
  },
  {
    id: 169,
    level: 6,
    number: 817,
    language: 'ko-kr',
    title: '금빛 물고기 이야기',
    topics: new Set(),
  },
  {
    id: 170,
    level: 6,
    number: 817,
    language: 'th-th',
    title: '금빛 물고기 이야기',
    topics: new Set(),
  },
  {
    id: 171,
    level: 6,
    number: 817,
    language: 'vi-vn',
    title: '금빛 물고기 이야기',
    topics: new Set(),
  },
  {
    id: 172,
    level: 6,
    number: 817,
    language: 'zh-cn',
    title: '금빛 물고기 이야기',
    topics: new Set(),
  },
  {
    id: 173,
    level: 6,
    number: 818,
    language: 'en-ph',
    title: '물의 축제 송끄란',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 174,
    level: 6,
    number: 818,
    language: 'ko-kr',
    title: '물의 축제 송끄란',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 175,
    level: 6,
    number: 818,
    language: 'th-th',
    title: '물의 축제 송끄란',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 176,
    level: 6,
    number: 818,
    language: 'vi-vn',
    title: '물의 축제 송끄란',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 177,
    level: 6,
    number: 818,
    language: 'zh-cn',
    title: '물의 축제 송끄란',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 178,
    level: 6,
    number: 819,
    language: 'en-ph',
    title: '빛의 축제 러이끄라통',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 179,
    level: 6,
    number: 819,
    language: 'ko-kr',
    title: '빛의 축제 러이끄라통',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 180,
    level: 6,
    number: 819,
    language: 'th-th',
    title: '빛의 축제 러이끄라통',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 181,
    level: 6,
    number: 819,
    language: 'vi-vn',
    title: '빛의 축제 러이끄라통',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 182,
    level: 6,
    number: 819,
    language: 'zh-cn',
    title: '빛의 축제 러이끄라통',
    topics: new Set([
      '생활',
    ]),
  },
  {
    id: 183,
    level: 6,
    number: 820,
    language: 'en-ph',
    title: '신나는 태국 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 184,
    level: 6,
    number: 820,
    language: 'ko-kr',
    title: '신나는 태국 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 185,
    level: 6,
    number: 820,
    language: 'th-th',
    title: '신나는 태국 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 186,
    level: 6,
    number: 820,
    language: 'vi-vn',
    title: '신나는 태국 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 187,
    level: 6,
    number: 820,
    language: 'zh-cn',
    title: '신나는 태국 여행',
    topics: new Set([
      '모험',
    ]),
  },
  {
    id: 188,
    level: 6,
    number: 821,
    language: 'en-ph',
    title: '병아리 별',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 189,
    level: 5,
    number: 821,
    language: 'ko-kr',
    title: '병아리 별',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 190,
    level: 5,
    number: 821,
    language: 'th-th',
    title: '병아리 별',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 191,
    level: 5,
    number: 821,
    language: 'vi-vn',
    title: '병아리 별',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 192,
    level: 5,
    number: 821,
    language: 'zh-cn',
    title: '병아리 별',
    topics: new Set([
      '동물',
    ]),
  },
  {
    id: 193,
    level: 3,
    number: 901,
    language: 'ko-kr',
    title: '단군설화',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 194,
    level: 3,
    number: 902,
    language: 'ko-kr',
    title: '김수로와 허황옥',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 195,
    level: 4,
    number: 903,
    language: 'ko-kr',
    title: '바보 온달과 평강 공주',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 196,
    level: 4,
    number: 904,
    language: 'ko-kr',
    title: '김유신',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 197,
    level: 3,
    number: 905,
    language: 'ko-kr',
    title: '한국의 전통 음식',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 198,
    level: 3,
    number: 906,
    language: 'ko-kr',
    title: '한국의 전통 명절',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 199,
    level: 4,
    number: 907,
    language: 'ko-kr',
    title: '신사임당',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 200,
    level: 4,
    number: 908,
    language: 'ko-kr',
    title: '세종대왕: 임금님이 된 책벌레 왕자',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 201,
    level: 4,
    number: 909,
    language: 'ko-kr',
    title: '왕의 생활',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 202,
    level: 4,
    number: 910,
    language: 'ko-kr',
    title: '강감찬',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 203,
    level: 4,
    number: 911,
    language: 'ko-kr',
    title: '박혁거세와 알영',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 204,
    level: 3,
    number: 912,
    language: 'ko-kr',
    title: '제주도의 세 시조',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 205,
    level: 4,
    number: 913,
    language: 'ko-kr',
    title: '고구려를 세운 주몽',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 206,
    level: 4,
    number: 914,
    language: 'ko-kr',
    title: '백제를 세운 온조',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 207,
    level: 4,
    number: 915,
    language: 'ko-kr',
    title: '고려를 세운 태조 왕건',
    topics: new Set([
      '역사',
    ]),
  },
  {
    id: 208,
    level: 4,
    number: 916,
    language: 'ko-kr',
    title: '조선을 세운 태조 이성계',
    topics: new Set([
      '역사',
    ]),
  },
];

export default stories;
